evaluation:
  data_source_name: Bike_Sharing_Demand
  scores:
    - neg_mean_absolute_error
    - neg_root_mean_squared_error
  pipeline_name: binned_time_poly_kernel_approx
  cross_validation:
    splitter: sklearn.model_selection.TimeSeriesSplit
    params:
      n_splits: 5
      gap: 48
      max_train_size: 10000
      test_size: 1000

data_sources:
  - name: Preprocessed_Bike_Sharing_Demand
    callable: auxiliarymodule.fetch_preprocess_bike_sharing
    kwargs:
      name: Bike_Sharing_Demand
      version: 2

pipelines:
  - name: binned_time_poly_kernel_approx
    steps:
      - column_transformer:
          - transformers:
              - name: categorical
                columns:
                  - weather
                  - season
                  - holiday
                  - workingday
                transformer:
                  estimator: sklearn.preprocessing.OneHotEncoder

              - name: time
                columns:
                  - month
                  - weekday
                  - hour
                transformer:
                  estimator: sklearn.preprocessing.KBinsDiscretizer
                  params:
                    bins: 5

          - remainder:
              estimator: sklearn.preprocessing.MinMaxScaler

      - estimator: sklearn.kernel_approximation.Nystroem
        params:
          n_components: 300
          kernel: poly
          degree: 2
          random_state: 0

      - estimator: sklearn.linear_model.RidgeCV
        params:
          alphas:
            callable: numpy.logspace
            args:
              - -6
              - 6
              - 25
